---
resources:
- name: blog-develop
  type: git
  source:
    uri: git@github.com:robdimsdale/blog
    branch: develop
    private_key: {{private-key}}

- name: blog-master
  type: git
  source:
    uri: git@github.com:robdimsdale/blog
    branch: master
    private_key: {{private-key}}

jobs:
- name: build-site-develop
  plan:
  - get: blog-develop
    trigger: true
  - task: build-site
    file: blog-develop/scripts/ci/build_site_develop.yml

- name: deploy-site-develop
  plan:
  - get: blog-develop
    trigger: true
    passed: [build-site-develop]
  - task: deploy-site-develop
    file: blog-develop/scripts/ci/deploy_site_develop.yml
    config:
      params:
        CF_USER: {{cf-user}}
        CF_PASSWORD: {{cf-password}}
        CF_ORG: {{cf-org-develop}}
        CF_SPACE: {{cf-space-develop}}
        CF_APPLICATION: {{cf-application-develop}}
        STATIC_FILE_AUTH: {{static-file-auth-develop}}

- name: build-site-master
  plan:
  - get: blog-master
    trigger: true
  - task: build-site
    file: blog-master/scripts/ci/build_site_master.yml
